name: zefaf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+15

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider:
  hive:
  dio:
  adaptive_action_sheet:
  flutter_dropdown_alert:
  ionicons:
  permission_handler:
  flutter_spinkit:
  flutter_slider_indicator:
  phoenix_native:
  flutter_launcher_icons:
  cached_network_image:
  awesome_dialog:
  flutter_screenshot_switcher:
  custom_pop_up_menu:
  advanced_icon:
  gestures:
  path_provider:
  dismissible_page:
  get: ^4.6.5
  custom_timer: ^0.0.6
  image_picker:
  babstrap_settings_screen:
  whatsapp_unilink:
  flutter_launch:
  url_launcher:
  store_redirect:
  flutter_share:
  get_storage:
  toggle_switch:
  glass:
  lottie:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  animated_text_kit:
  convex_bottom_bar:
  flutter_audio_manager_plus:
  proximity_sensor:
  assets_audio_player:
  chat_bubbles:
  pay:
  empty_widget:
  flutter_ringtone_player:
  gradient_borders:
  widget_circular_animator:
  flutter_datetime_picker:
    git:
      url: https://github.com/HasanAlqaisi/flutter_datetime_picker.git
  flutter_incall_manager:
    git: https://github.com/manozzreddy/flutter-incall-manager.git
  flutter_webrtc:
  dough:
  sdp_transform: ^0.3.0
  socket_io_client: ^1.0.1
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.2.1
  in_app_purchase_storekit: ^0.3.4
  get_it: ^7.2.0
  fluttertoast: 8.1.2
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.0

flutter_icons:
  android: true
  image_path: "assets/logo/logoIcon2.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/flags/
    - assets/icons/
    - assets/call/
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf