name: zefaf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.52+52

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_inappwebview: ^6.1.5
  in_app_purchase: ^3.2.0
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.1.0
  http: 
  get: 4.6.6
  sentry_flutter: ^8.9.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logoIcon2.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/font/


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf
