const Map<String,String> ar = {
  'Login' : 'دخول',
  'Welcome to E-Expense' : 'مرحبا بكم في [ TAMIRCI ]',
  'Signup' : 'تسجيل',
  'USER NAME' : 'اسم المستخدم',
  'PHONE' : 'الهاتف',
  'PASSWORD' : 'الرمز',
  'SIGN IN' : 'تسجيل دخول',
  'i dont have an account' : 'لا امتلك حساب',
  'SIGNUP' : 'تسجيل',
  'error phone number' : 'خطأ في رقم الهاتف',
  'password is less than 6' : 'الرمز اقل من 6',
  'error name' : 'خطأ في الاسم',
  'error' : 'خطأ',
  'done' : 'تم',
  'Registered successfully' : 'تمت بنجاح',
  'Please verify your login information' : 'يرجى التحقق من معلومات تسجيل الدخول الخاصة بك',
  'You have signed in successfully' : 'لقد قمت بتسجيل الدخول بنجاح',
  'New Invoice' : 'طلب جديد',
  'User Name' : 'أسم العميل',
  'Phone Number' : 'الجوال',
  'Home Phone' : 'الهاتف الأرضي',
  'Email' : 'البريد الإلكتروني',
  'Address' : 'العنوان',
  'Street' : 'الشارع',
  'Building' : 'البناء',
  'Floor' : 'الطابق',
  'Apartment' : 'الشقة',
  'Not' : 'ملاحظة',
  'Country' : 'الدولة',
  'City' : 'المحافظة',
  'Choose From Map' : 'اختر من الخريطة',
  'Search For A Destination' : 'ابحث عن وجهة',
  'Name of the destination' : 'اسم الوجهة',
  'Map' : 'خريطة',
  'Select Brand' :'الماركة',
  'Select Machine Type' : 'نوع الجهاز',
  'Select Malfunction' : 'نوع العطل',
  'No image selected.' : 'لا يوجد صورة',
  'Take a picture of the device' : 'صورة الجهاز',
  'Save' : 'ارسال الطلب',
  'Created Date' : 'تاريخ الطلب',
  'updated Date' : 'اخر تحديث',
  'Name' : 'الاسم',
  'Technical' : 'الفني',
  'Customer' : 'الزبون',
  'machine price' : 'سعر الجهاز',
  'Cost of maintenance' : 'Cost of maintenance',
  'Brand' : 'الماركة',
  'Malfunction' : 'العطل',
  'Type' : 'النوع',
  'Services' : 'الخدمات',
  'My Invoice' : 'فواتيري',
  'In progress Invoice' : 'قيد العمل',
  'Ended Invoice' : 'الفواتير المنتهية',
  'Create a new invoice' : 'عمل طلب جديد',
  'All My Invoice' : 'كل الفواتير',
  'Invoices are in progress' : 'قيد العمل',
  'Finished Invoice' : 'فواتير منتهية',
  'Cancel' : 'الغاء',
  'No Data' : 'لا يوجد بيانات',
  'Error' : 'خطأ',
  'Canceled' : 'تم الغاء',
  'Finished' : 'تم الانتهاء',
  'Take' : 'اخذ',
  'Malfunction price' : 'سعر العطل',
  'Price' : 'السعر',
  'chose' : 'اختر',
  'submit' : 'تم',
  'warranty' : 'الكفالة',
  'Year' : 'السنة',
  'Complete' : 'تمت',
  'User' : 'المستخدم',
  'Years' : 'السنوات',
  'Total Price' : 'مجموع الكلي',
  'Share' : 'مشاركة',
  'Home' : 'الرئيسية',
  'Create New' : 'إنشاء طلب',
  'progress_invoices' : 'قيد الانتظار',
  'finished_invoice' : 'منتهية',
  'Language' : 'اللغة',
  'cancel' : 'الغاء',
  'yes' : 'نعم',
  'msg' : 'هل انت متأكد ؟',
  'sign out' : 'تسجيل الخروج',
  'Whatever your needs are' : 'مهما كانت احتياجاتك',
};