const Map<String,String> en = {
  'Login' : 'Login',
  'Welcome to E-Expense' : 'Welcome to [ TAMIRCI ]',
  'Signup' : 'Signup',
  'USER NAME' : 'USER NAME',
  'PHONE' : 'PHONE',
  'PASSWORD' : 'PASSWORD',
  'SIGN IN' : 'SIGN IN',
  'i dont have an account' : 'i dont have an account',
  'SIGNUP' : 'SIGNUP',
  'error phone number' : 'error phone number',
  'password is less than 6' : 'password is less than 6',
  'error name' : 'error name',
  'error' : 'error',
  'done' : 'done',
  'Registered successfully' : 'Registered successfully',
  'Please verify your login information' : 'Please verify your login information',
  'You have signed in successfully' : 'You have signed in successfully',
  'New Invoice' : 'New Invoice',
  'User Name' : 'User Name',
  'Phone Number' : 'Phone Number',
  'Home Phone' : 'Home Phone',
  'Email' : 'Email',
  'Address' : 'Address',
  'Street' : 'Street',
  'Building' : 'Building',
  'Floor' : 'Floor',
  'Apartment' : 'Apartment',
  'Not' : 'Not',
  'Country' : 'Country',
  'City' : 'City',
  'Choose From Map' : 'Choose From Map',
  'Search For A Destination' : 'Search For A Destination',
  'Name of the destination' : 'Name of the destination',
  'Map' : 'Map',
  'Select Brand' :'Select Brand',
  'Select Machine Type' : 'Select Machine Type',
  'Select Malfunction' : 'Select Malfunction',
  'No image selected.' : 'No image selected.',
  'Take a picture of the device' : 'Take a picture of the device',
  'Save' : 'Send',
  'Created Date' : 'Created Date',
  'updated Date' : 'updated Date',
  'Name' : 'Name',
  'Technical' : 'Technical',
  'Customer' : 'Customer',
  'machine price' : 'machine price',
  'Cost of maintenance' : 'Cost of maintenance',
  'Brand' : 'Brand',
  'Malfunction' : 'Malfunction',
  'Type' : 'Type',
  'Services' : 'Services',
  'My Invoice' : 'My Invoice',
  'In progress Invoice' : 'In progress Invoice',
  'Ended Invoice' : 'Ended Invoice',
  'Create a new invoice' : 'Create a new invoice',
  'All My Invoice' : 'All My Invoice',
  'Invoices are in progress' : 'Invoices are in progress',
  'Finished Invoice' : 'Finished Invoice',
  'Cancel' : 'Cancel',
  'No Data' : 'No Data',
  'Error' : 'Error',
  'Canceled' : 'Canceled',
  'Finished' : 'Finished',
  'Take' : 'Take',
  'Malfunction price' : 'Malfunction price',
  'Price' : 'Price',
  'chose' : 'chose',
  'submit' : 'submit',
  'warranty' : 'warranty',
  'Year' : 'Year',
  'Complete' : 'Complete',
  'User' : 'User',
  'Years' : 'Years',
  'Total Price' : 'Total Price',
  'Share' : 'Share',
  'Home' : 'Home',
  'Create New' : 'Create New',
  'progress_invoices' : 'In progress',
  'finished_invoice' : 'Finished',
  'Language' : 'Language',
  'cancel' : 'cancel',
  'msg' : 'are you sure ?',
  'yes' : 'yes',
  'sign out' : 'sign out',
  'Whatever your needs are' : 'Whatever your needs are',




};


// font  Montserrat