const Map<String,String> tr = {
  'Login' : 'giriş',
  'Welcome to E-Expense' : 'Hoşgeldiniz[ TAMIRCI ]',
  'Signup' : 'Kayıt Ol',
  'USER NAME' : 'KULLANICI ADI',
  'PHONE' : 'TELEFON',
  'PASSWORD' : 'ŞİFRE',
  'SIGN IN' : 'GİRİŞ YAP',
  'i dont have an account' : 'hesabım yok',
  'SIGNUP' : 'Kayıt Ol',
  'error phone number' : 'hata telefon numarası',
  'password is less than 6' : 'şifre 6dan az olduğu',
  'error name' : 'hata adı',
  'error' : 'hata',
  'done' : 'tamam',
  'Registered successfully' : 'başarıyla Kayıtlı',
  'Please verify your login information' : 'Lütfen giriş bilgilerinizi doğrulayın',
  'You have signed in successfully' : 'Başarıyla giriş yaptınız',
  'New Invoice' : 'Yeni fatura',
  'User Name' : 'Kullanıcı adı',
  'Phone Number' : 'Telefon numarası',
  'Home Phone' : 'Ev telefonu',
  'Email' : 'E-posta',
  'Address' : 'Adres',
  'Street' : 'sokak',
  'Building' : 'Bina',
  'Floor' : 'Zemin',
  'Apartment' : 'Apartman',
  'Not' : 'Değil',
  'Country' : 'Ülke',
  'City' : 'Şehir',
  'Choose From Map' : 'Haritadan Seçin',
  'Search For A Destination' : 'Bir Hedef Ara',
  'Name of the destination' : 'Hedefin adı',
  'Map' : 'Harita',
  'Select Brand' :'Marka seçiniz',
  'Select Machine Type' : 'Makine Tipini Seçin',
  'Select Malfunction' : 'Arıza Seçin',
  'No image selected.' : 'Seçilen resim yok.',
  'Take a picture of the device' : 'Cihazın fotoğrafını çekin',
  'Save' : 'gönder',
  'Created Date' : 'Oluşturulma Tarihi',
  'updated Date' : 'güncellenmiş tarihi',
  'Name' : 'ad',
  'Technical' : 'Teknik',
  'Customer' : 'Müşteri',
  'machine price' : 'makine fiyatı',
  'Cost of maintenance' : 'Bakım maliyeti',
  'Brand' : 'Marka',
  'Malfunction' : 'Arıza',
  'Type' : 'Tür',
  'Services' : 'Hizmetler',
  'My Invoice' : 'Benim Fatura',
  'In progress Invoice' : 'İlerleme Fatura yılında',
  'Ended Invoice' : 'Sona Ermiş Fatura',
  'Create a new invoice' : 'Yeni fatura oluştur',
  'All My Invoice' : 'Tüm Faturam',
  'Invoices are in progress' : 'Faturalar devam etmektedir',
  'Finished Invoice' : 'Biten Fatura',
  'Cancel' : 'İptal etmek',
  'No Data' : 'Veri yok',
  'Error' : 'Hata',
  'Canceled' : 'İptal edildi',
  'Finished' : 'bitmiş',
  'Take' : 'Al',
  'Malfunction price' : 'Arıza fiyatı',
  'Price' : 'Fiyat',
  'chose' : 'seç',
  'submit' : 'Sunmak',
  'warranty' : 'garanti',
  'Year' : 'Yıl',
  'Complete' : 'Tamamlayınız',
  'User' : 'Kullanıcı',
  'Years' : 'Yıllar',
  'Total Price' : 'Toplam fiyat',
  'Share' : 'Paylaş',
  'Home' : 'Ana Sayfa',
  'Create New' : 'Yeni Oluştur',
  'progress_invoices' : 'ilerleme faturaları',
  'finished_invoice' : 'bitmiş fatura',
  'Language' : 'Dil',
  'cancel' : 'iptal',
  'yes' : 'evet',
  'msg' : 'emin misin ?',
  'sign out' : 'çıkış',
  'Whatever your needs are' : 'İhtiyaçlarınız ne olursa olsun',
};